---
abstract: 'Prepend converted PATH_INFO to QUERY_STRING'
author:
  - 'Yasutaka ATARASHI <yakex@cpan.org>'
build_requires:
  HTTP::Request::Common: 0
  JSON: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300029, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-PathToQuery
requires:
  Plack: 0
  URI::Escape: 0
  parent: 0
  perl: 5.006
version: v0.0.1
